export const cn = {
  copy: '复制',
  copied: '已复制',
  yes: '是',
  no: '否',
  approving: '授权中',
  insufficient: '余额不足',
  unableAddress: '推荐链接无效',
  approve: '授权',
  bind: '上级地址',
  pay: '支付',
  inviteNum: '推荐人数',
  enter: '输入金额',
  balance: '我的资金',
  rewards: '奖励',
  claim: '领取',
  withdraw: '撤出',
  save: '存入',
  buy: '购买一个节点',
  inviteLink: '推荐链接',
  totalSupply: '总量',
  home: {
    title: '首页',
    token: '代币FN',
    rule1: '1亿',
    rule2: '4000万底池+2000万节点锁仓',
    rule3: '2000万节点权益，锁仓一年',
    rule4: '1500万定期利息',
    rule5: '2000万定期推荐奖励',
    rule6: '500万活期利息',
    text1: '买卖滑点6%，2%回流， 2%技术营销，2%节点分 红，转账无滑手续费',
    text2: '1.活期存币，收益和本金可随存随取',
    text3: '2.定期存币，收益可限时领取，本金30天期满后可提取， 也可以承担违约金提前强制解除'
  },
  node: {
    title: '节点',
    buy: '购买',
    bought: '已购买',
    rewards: '已获得奖励',
    nodes: '全网节点',
    isNode: '是否节点',
    totalRewards: '全网总分红',
    preRewards: '每节点分红',
    claimedRewards: '已领取分红',
    ableRewards: '可领取分红',
    claim: '领取分红'
  },
  earn: {
    title: 'farm',
    fixed: '定期',
    fixedDeposit: '定期存款',
    demand: '活期',
    demandDepositL: '活期存款',
    save: '存入',
    s: '存',
    claim: '奖励',
    tvl: '年化收益率',
    saveToken: '存币',
    invite: '节点推荐',
    myRewards: '已获得奖励',
    minAmount: '最低存币10000 FN'
  },
  sport: {
    title: 'sport'
  }
}
