export const en = {
  implemeting: 'This section is still implemeting.',
  back: 'Please come back later',
  coming: 'Coming soon',
  copy: 'copy',
  copied: 'copied',
  yes: 'yes',
  no: 'no',
  enter: 'Enter Amount',
  approving: 'Approving',
  insufficient: 'Insufficient balance',
  unableAddress: 'Link is not available',
  approve: 'approve',
  bind: 'Bind address',
  pay: 'pay',
  inviteNum: 'Invited',
  balance: 'balance',
  rewards: 'Rewards',
  claim: 'Claim',
  withdraw: 'Withdraw',
  save: 'Save',
  buy: 'Buy a node',
  inviteLink: 'Invite link',
  minAmount: 'At least 10000 FN',
  totalSupply: 'Total Supply',
  home: {
    title: 'Home',
    token: 'FN Token',
    rule1: 'Total supply：100 Million',
    rule2: '40 Million for Pool',
    rule3: '20 Million  for node share',
    rule4: '15 Million for fixed term deposit interest',
    rule5: '20 Million for fixed term deposit referral reward',
    rule6: '5 Million for current deposit interest',
    text1: 'Buy and Sell:  2% LP fee, 2% marketing fee , 2% node reward fee. Transfer: no fees',
    text2: '1: current deposit, claim reward and withdraw at any time',
    text3: '2: fixed term deposit, claim reward at any time, withdraw after 30 days, or force withdraw with extra fine'
  },
  node: {
    title: 'Node',
    buy: 'Buy',
    bought: 'bought',
    rewards: 'My Rewards',
    nodes: 'Nodes',
    isNode: 'IsNode',
    totalRewards: 'Rewards',
    preRewards: 'Each node',
    claimedRewards: 'Claimed',
    ableRewards: 'Available',
    claim: 'Claim Rewards'
  },
  earn: {
    title: 'Farm',
    fixed: 'Fixed',
    fixedDeposit: 'Fixed deposit',
    demand: 'Current',
    demandDepositL: 'Current depositL',
    save: 'Save',
    s: 'Save',
    claim: 'Claim',
    tvl: 'APY',
    saveToken: 'Stake',
    invite: 'Invite node',
    myRewards: 'Rewards'
  },
  sport: {
    title: 'sport'
  },
  detail: 'Detail >',
  contract: 'Contract',
  startTime: 'Start Time',
  endTime: 'End Time',
  totalReward: 'Total Reward',
  dailyReward: 'Daily Reward',
  realizedReward: 'Realized Reward',
  tvl: 'TVL'
}
